name: admin-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/admin/**"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
            
    steps:
      - name: check out repository
        uses: actions/checkout@v3

      - name: setup directory
        run: cd packages/admin

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.ADMIN_ACCESS }}
          github_token: ${{ secrets.PICK_ACCESS_TOKEN }}
          
