name: xquare-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  get-diff-workspace:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "2"
          token: ${{ secrets.PICK_ACCESS_TOKEN }}

      - name: diff-workspace
        id: set-matrix
        run: echo "::set-output name=matrix::{\"workspaces\":[$(yarn workspaces list --json | sed -n '2,$p' | sed 's/.*"name":"\([^"]*\)".*/\1/' | tr "\n" ",")]}"

  build:
    permissions:
      id-token: write
      contents: read
    needs: get-diff-workspace
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-diff-workspace.outputs.matrix) }}

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Generate Environment Variables File
        run: |
          for workspace in ${{ fromJson(needs.get-diff-workspace.outputs.matrix).workspaces }}; do
            if [ "$workspace" == "keeper" ]; then
              echo "REACT_APP_PUBLIC_PICK_BASE_URL=$REACT_APP_PUBLIC_PICK_BASE_URL" >> packages/$workspace/.env
            else
              echo "NEXT_PUBLIC_PICK_BASE_URL=$NEXT_PUBLIC_PICK_BASE_URL" >> packages/$workspace/.env 
              echo "NEXT_PUBLIC_HTTP_ONLY=$NEXT_PUBLIC_HTTP_ONLY" >> packages/$workspace/.env 
            fi
          done
        env:
          REACT_APP_PUBLIC_PICK_BASE_URL: ${{ secrets.BASE_URL }}
          NEXT_PUBLIC_PICK_BASE_URL: ${{ secrets.BASE_URL }}
          NEXT_PUBLIC_HTTP_ONLY: ${{ secrets.NEXT_PUBLIC_HTTP_ONLY }}

      - name: Deploy to xquare (Admin)
        if: contains(needs.get-diff-workspace.outputs.matrix.workspaces, 'admin')
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.ADMIN_ACCESS }}
          github_token: ${{ secrets.PICK_ACCESS_TOKEN }}

      - name: Deploy to xquare (Teacher)
        if: contains(needs.get-diff-workspace.outputs.matrix.workspaces, 'teacher')
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.TEACHER_ACCESS }}
          github_token: ${{ secrets.PICK_ACCESS_TOKEN }}

      - name: Deploy to xquare (Keeper)
        if: contains(needs.get-diff-workspace.outputs.matrix.workspaces, 'keeper')
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.KEEPER_ACCESS }}
          github_token: ${{ secrets.PICK_ACCESS_TOKEN }}
